name: Generare documentatie Doxygen

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generare documentatie Doxygen
        uses: Doxygen-Action@v1.0.0
        with:
          doxygen-config: Doxyfile
      - name: Salvare documentatie ca artefact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs
